# NOTE: This file is not part of the official higan source, it's been added
# to help build WIP binaries with minimal fuss.

image: ubuntu:latest

bsnes-linux-x86_64-binaries:
  script:
    - apt-get update && apt-get -y install build-essential libgtk2.0-dev libpulse-dev mesa-common-dev libgtksourceview2.0-dev libcairo2-dev libsdl2-dev libxv-dev libao-dev libopenal-dev libudev-dev
    - make -C higan target=bsnes
    - mkdir bsnes-nightly
    - cp -a higan/out/bsnes bsnes-nightly/bsnes
    - cp -a shaders bsnes-nightly/
    - cp -a GPLv3.txt bsnes-nightly/
  artifacts:
    paths:
      - bsnes-nightly/*

bsnes-windows-x86_64-binaries:
  script:
    - apt-get update && apt-get -y install build-essential mingw-w64
    - make -C higan target=bsnes platform=windows compiler="x86_64-w64-mingw32-g++" windres="x86_64-w64-mingw32-windres"
    - mkdir bsnes-nightly
    - cp -a higan/out/bsnes bsnes-nightly/bsnes.exe
    - cp -a shaders bsnes-nightly/
    - cp -a GPLv3.txt bsnes-nightly/
  artifacts:
    paths:
      - bsnes-nightly/*
